// GENERADO automáticamente por scripts/gen-ship-info.mjs — no editar a mano.
// Descripciones: Wookieepedia (starwars.fandom.com). Specs: SWAPI (swapi.info).
// Indexado por nombre de nave normalizado (sin acentos, minúsculas).
// Regenerar:  node scripts/gen-ship-info.mjs

export interface SpecsNave {
  model?: string;
  manufacturer?: string;
  crew?: string;
  passengers?: string;
  maxSpeed?: string;
  hyperdrive?: string;
}

export interface InfoNave {
  descripcion: string;
  specs: SpecsNave;
}

export const INFO_NAVES: Record<string, InfoNave> = {
  "a-wing": { descripcion: "The RZ-1 A-wing interceptor, also known as the RZ-1 A-wing starfighter, was a wedge-shaped starfighter manufactured by Kuat Systems Engineering, which took design inspiration from the Republic starfighters of the Clone Wars.", specs: { model: "RZ-1 A-wing Interceptor", manufacturer: "Alliance Underground Engineering, Incom Corporation", crew: "1", passengers: "0", maxSpeed: "1300", hyperdrive: "1.0" } },
  "arc-170": { descripcion: "The Aggressive ReConnaissance-170 starfighter, also known simply as the ARC-170 Starfighter, was a heavy-duty model of starfighter used by the Galactic Republic during the Clone Wars and was considered the latest in fighter technology.", specs: { model: "Aggressive Reconnaissance-170 starfighte", manufacturer: "Incom Corporation, Subpro Corporation", crew: "3", passengers: "0", maxSpeed: "1000", hyperdrive: "1.0" } },
  "b-wing": { descripcion: "The A/SF-01 B-wing starfighter, also designated as the A/SF-01 B-wing assault starfighter, more commonly referred to as the B-wing, was a heavily armed Rebel Alliance single-pilot starfighter and bomber designed by the starship engineer Quarrie and manufactured by Slayn & Korpil.", specs: { model: "A/SF-01 B-wing starfighter", manufacturer: "Slayn & Korpil", crew: "1", passengers: "0", maxSpeed: "950", hyperdrive: "2.0" } },
  "belbullab-22": { descripcion: "The Belbullab-22 heavy starfighter was a single-pilot heavy starfighter model manufactured by Feethan Ottraw Scalable Assemblies. It was the heaviest fighter in the Confederacy of Independent Systems naval forces during the Clone Wars against the Galactic Republic and the only fighter crewed by a pilot.", specs: { model: "Belbullab-22 starfighter", manufacturer: "Feethan Ottraw Scalable Assemblies", crew: "1", passengers: "0", maxSpeed: "1100", hyperdrive: "6" } },
  "caza": { descripcion: "The TIE/ln space superiority starfighter, also called the TIE/ln or simply the TIE fighter, was the signature starfighter of the Galactic Empire and symbol of its space superiority.", specs: {} },
  "cazadarkvader": { descripcion: "The TIE Advanced x1, also referred to as the TIE Advanced Fighter X1 or simply TIE/ad, was an advanced prototype starfighter that was part of the TIE fighter series manufactured by Sienar Fleet Systems. Darth Vader notably flew a TIE Advanced x1.", specs: { model: "Twin Ion Engine Advanced x1", manufacturer: "Sienar Fleet Systems", crew: "1", passengers: "0", maxSpeed: "1200", hyperdrive: "1.0" } },
  "chimaera": { descripcion: "The Chimaera was a modified Imperial I-class Star Destroyer captained by Imperial officer Thrawn during the Galactic Civil War.", specs: {} },
  "delta-7 aethersprite": { descripcion: "The Delta-7 Aethersprite-class light interceptor, also known as the Delta-7 Aethersprite-class Jedi starfighter, Delta-7 Jedi starfighter, or Delta-7 Jedi Interceptor, and commonly referred to as the Jedi starfighter, was a starfighter model designed by Kuat Systems Engineering and used by the Jedi Order before and dur…", specs: {} },
  "devastator": { descripcion: "The Devastator was an Imperial I-class Star Destroyer of the Imperial Navy, famous for its tenure as the flagship of the Dark Lord of the Sith, Darth Vader. Under Vader's command, the Devastator participated in the Battle of Scarif and the capture of the Tantive IV.", specs: {} },
  "droid tri-fighter": { descripcion: "The droid tri-fighter was a model of droid starfighter utilized by the Confederacy of Independent Systems during the Clone Wars. It was specifically designed to engage and excel in heavy dogfighting.", specs: {} },
  "ebon hawk": { descripcion: "The Ebon Hawk was a Dynamic-class freighter and a smuggler ship that rose to fame due to its use around the time of the Jedi Civil War.", specs: {} },
  "eta2 - interceptor": { descripcion: "The Eta-2 Actis-class light interceptor, also known as the Eta-2 Actis Jedi Interceptor, Eta-2 light interceptor, Eta-2 interceptor or simply Actis, was a starfighter used by the Jedi during the Clone Wars.", specs: {} },
  "executor": { descripcion: "The Executor was an Executor-class Star Dreadnought and personal flagship of the Sith Lord Darth Vader and was the most powerful vessel ever created by the Galactic Empire.", specs: { model: "Executor-class star dreadnought", manufacturer: "Kuat Drive Yards, Fondor Shipyards", crew: "279,144", passengers: "38000", hyperdrive: "2.0" } },
  "fang fighter": { descripcion: "The Fang-class Protectorate fighter, also known as Fang fighter, Protectorate fighter, or as the Protector Fang Fighter, was a starfighter manufactured by SoroSuub Corporation and MandalMotors and used by the Mandalorian Protectors.", specs: {} },
  "finalizer": { descripcion: "The Finalizer was a Resurgent-class Star Destroyer of the naval forces of the First Order. It served as the flagship of General Armitage Hux and Kylo Ren.", specs: {} },
  "gauntlet fighter": { descripcion: "The Kom'rk-class fighter/transport, also known as Kom'rk Class fighter transport or the Gauntlet starfighter, was a type of starfighter and troop transport used by the Mandalorian splinter faction known as Death Watch during the Clone Wars.", specs: {} },
  "ghost": { descripcion: "The Ghost was a modified VCX-100 light freighter owned by the Twi'lek Hera Syndulla that was used by the Spectres rebel cell during the Age of the Empire. As part of the rebellion, the Ghost saw actions on numerous missions and skirmishes against the forces of the Galactic Empire.", specs: {} },
  "hyena bomber": { descripcion: "Hyena-class Droid Fighter/Bombers, also known as Hyena-class Droid Bombers, Hyena-class bombers, Hyena droid bombers, or Hyena bombers, were droid starfighters manufactured by Baktoid Armor Workshop. They were designed for heavy ordnance bombing runs.", specs: {} },
  "invisible hand": { descripcion: "The Invisible Hand was a modified Providence-class Dreadnought that served in the naval forces of the Confederacy of Independent Systems as the flagship of the navy and the command ship of Kaleesh Separatist General Grievous during the Clone Wars.", specs: {} },
  "malevolence": { descripcion: "The Malevolence was a Subjugator-class heavy cruiser that served within the naval forces of the Confederacy of Independent Systems, and was used as the flagship of Kaleesh Separatist General Grievous during the Clone Wars.", specs: {} },
  "millennium falcon": { descripcion: "The Millennium Falcon, originally designated YT 492727ZED and formerly known as the Stellar Envoy, and registered or known under various aliases and pseudonyms including Broken Bell, Corell's Pride, Close Shave, Fickle Flyer, Foul Matter, Graphite Skipper, Jin-Den Smoke, Longshot, Lost and Found, Star Princess, Sunfigh…", specs: { model: "YT-1300 light freighter", manufacturer: "Corellian Engineering Corporation", crew: "4", passengers: "6", maxSpeed: "1050", hyperdrive: "0.5" } },
  "n-1 naboo starfighter": { descripcion: "The N-1 starfighter, also referred to as the Royal Naboo N-1 starfighter, Naboo N-1 starfighter, Naboo starfighter, N-1 fighter, or more simply, the N-1, was a single seat patrol craft developed by the Theed Palace Space Vessel Engineering Corps and used by the Royal Naboo Security Forces.", specs: {} },
  "naboo royal starship": { descripcion: "The J-type 327 Nubian royal starship was a starship model designed and built by Nubia Star Drives, Inc.. They used a sublight engine and a T-14 hyperdrive generator, also designed by Nubian Design Collective. The T-14 hyperdrive gave the J-type 327 Nubian a hyperdrive rating of 1.8.", specs: { model: "J-type 327 Nubian royal starship", manufacturer: "Theed Palace Space Vessel Engineering Corps, Nubia Star Drives", crew: "8", maxSpeed: "920", hyperdrive: "1.8" } },
  "outrider": { descripcion: "The Outrider was a YT-2400 light freighter owned by Dash Rendar Like other YT-2400 light freighters, it was manufactured by Corellian Engineering Corporation; could reach speeds of 800 kilometers per hour; was equipped with two double laser turrets, concussion missile launchers, and a class 2 hyperdrive; and measured 1…", specs: {} },
  "profundity": { descripcion: "The Profundity was an MC75 Star Cruiser commanded by Admiral Raddus that served in the Alliance Fleet. It was notably present during the Battle of Scarif.", specs: {} },
  "raven's claw": { descripcion: "The Raven's Claw was a fast light courier that replaced Kyle Katarn's old ship, the Moldy Crow.", specs: {} },
  "razor crest": { descripcion: "The Razor Crest was an ST-70 M-111 Razor Crest series used by the Mandalorian bounty hunter Din Djarin. Prior to the rise of the Galactic Empire, it served as a military patrol craft.", specs: {} },
  "resistance x-wing": { descripcion: "The T-70 X-wing starfighter, also known as the T-70 X-wing fighter, was a next-generation model of the X-wing starfighter utilized by the New Republic Defense Fleet as the successor to the T-65B X-wing starfighter, manufactured by Incom-FreiTek Corporation.", specs: {} },
  "resistance y-wing": { descripcion: "The BTA-NR2 Y-wing starfighter, also known as the Resistance Y-wing, was a variant of the Y-wing starfighter produced by Koensayr Manufacturing that was used by the New Republic and the Resistance.", specs: {} },
  "rogue-class starfighter": { descripcion: "The Rogue-class Porax-38 starfighter, also known simply as the Rogue-class starfighter, Porax-38 starfighter, or P-38 fighter, was a model of starfighter manufactured by Baktoid Armor Workshop and Buuper Torsckil Abbey Devices and used by the Confederacy of Independent Systems during the Clone Wars.", specs: {} },
  "rz-1 a-wing": { descripcion: "The RZ-1 A-wing interceptor, also known as the RZ-1 A-wing starfighter, was a wedge-shaped starfighter manufactured by Kuat Systems Engineering, which took design inspiration from the Republic starfighters of the Clone Wars.", specs: {} },
  "slave i": { descripcion: "Slave I, also spelled Slave One and also known as Boba Fett's starship and Jango Fett's starship, was a modified Firespray-31-class patrol and attack craft used by the infamous Mandalorian bounty hunter Jango Fett before the Clone Wars and later his unaltered cloned son, Boba Fett, just prior to the Fall of the Republi…", specs: { model: "Firespray-31-class patrol and attack", manufacturer: "Kuat Systems Engineering", crew: "1", passengers: "6", maxSpeed: "1000", hyperdrive: "3.0" } },
  "stinger mantis": { descripcion: "The Stinger Mantis, commonly known as the Mantis, was an S-161 \"Stinger\" XL luxury yacht owned and piloted by Greez Dritus. In 14 BBY, Dritus transported the former Jedi Cere Junda and Cal Kestis on the vessel as part of their secret mission to rebuild the Jedi Order.", specs: {} },
  "supremacy": { descripcion: "The Supremacy, disparagingly nicknamed \"Snoke's Boudoir,\" was a Mega-class Star Dreadnought that served as the flagship of Supreme Leader Snoke and the mobile capital of the First Order from within the Unknown Regions of the galaxy.", specs: {} },
  "tantive iv": { descripcion: "The Tantive IV was a CR90 corvette in the service of the House of Organa. The ship was a central player in the events at the beginning of the Galactic Civil War, serving as Princess Leia Organa's personal starship in the leadup to the Battle of Yavin.", specs: {} },
  "tie advanced v1": { descripcion: "The TIE/sk x1 experimental air superiority fighter, also known as the TIE/sk atmospheric fighter or simply the TIE striker, was a streamlined variant of the TIE fighter series starfighters used by the Galactic Empire, most notably during the Battle of Scarif.", specs: {} },
  "tie advanced x1": { descripcion: "The TIE Advanced x1, also referred to as the TIE Advanced Fighter X1 or simply TIE/ad, was an advanced prototype starfighter that was part of the TIE fighter series manufactured by Sienar Fleet Systems. Darth Vader notably flew a TIE Advanced x1.", specs: { model: "Twin Ion Engine Advanced x1", manufacturer: "Sienar Fleet Systems", crew: "1", passengers: "0", maxSpeed: "1200", hyperdrive: "1.0" } },
  "tie aggressor": { descripcion: "The TIE/ag \"Aggressor\" Starfighter, or simply the TIE Aggressor, was a multi-role superiority starfighter-strike fighter. Its specific role was a hybrid fighter/bomber.", specs: {} },
  "tie avenger": { descripcion: "The TIE Avenger prototype was a model of TIE series starfighter that was used by the Galactic Empire. The manufactured prototypes of the TIE Advanced x1 inspired future development of starfighters, which resulted in the creation of the TIE/IN interceptor and the TIE Avenger.", specs: {} },
  "tie bomber": { descripcion: "The TIE/sa tactical bomber, also known as the TIE Surface Assault Bomber, TIE/sa bomber or simply the TIE bomber, was a bombing variant of the TIE series used by the Galactic Empire. An evolution of the TIE/gt, the TIE bomber was their main source of anti-emplacement air-support.", specs: {} },
  "tie brute": { descripcion: "The TIE/rb heavy starfighter, more formally known as the TIE reinforcement battery heavy starfighter, and simply known as the heavy TIE fighter, TIE Brute, or the Infiltrator was a variant of the TIE fighter series starfighters used by the Galactic Empire, distinguished by its extra pod housing more powerful laser cann…", specs: {} },
  "tie dagger": { descripcion: "The TIE/dg starfighter, also known as the TIE Dagger was a type of Sith Eternal-affiliated TIE fighter series starship that was forged in secret by forces under the command of the reborn Darth Sidious, along with the Xyston-class Star Destroyer, the AAL-2100/9.5 atmospheric assault lander, and other new technology crea…", specs: {} },
  "tie defender": { descripcion: "The TIE/d \"Defender\" Multi-Role Starfighter, also called the TIE/D Defender or simply the TIE Defender, was an advanced experimental TIE series starfighter manufactured by Sienar Fleet Systems for the Imperial Navy of the Galactic Empire.", specs: {} },
  "tie interceptor": { descripcion: "The TIE/IN interceptor, also known as the TIE Interceptor, or TIE/in was a type of TIE fighter used by the Galactic Empire, most notably during the Battle of Endor. The interceptor was identifiable by the addition of four arrow-shaped panels tipped with laser cannons.", specs: {} },
  "tie phantom": { descripcion: "The TIE/ph \"Phantom\" Multi-Role Stealth Starfighter, also known simply as the TIE/ph phantom or the TIE phantom, was a class of stealth starfighter that was deployed by the Galactic Empire during the Imperial Era.", specs: {} },
  "tie reaper": { descripcion: "The TIE/rp Reaper attack lander, also known simply as the TIE Reaper, was a troop carrier variant of Sienar Fleet Systems's TIE fighter series used by the Galactic Empire.", specs: {} },
  "tie silencer": { descripcion: "The TIE/vn space superiority fighter, As such, the fighter was engineered for speed and handling, though lesser pilots were still often overwhelmed and unable to maintain control of the nimble ship.", specs: {} },
  "tie striker": { descripcion: "The TIE/sk x1 experimental air superiority fighter, also known as the TIE/sk atmospheric fighter or simply the TIE striker, was a streamlined variant of the TIE fighter series starfighters used by the Galactic Empire, most notably during the Battle of Scarif.", specs: {} },
  "tie whisper": { descripcion: "The TIE/wi interceptor, also referred to as the TIE whisper or simply the whisper, was a First Order TIE fighter series interceptor used during the war against the Resistance. During the war, Supreme Leader Kylo Ren utilised his modified TIE whisper in the search for Exegol and to confront Rey on the planet Pasaana.", specs: {} },
  "u-wing": { descripcion: "The UT-60D U-wing starfighter/support craft, also designated as the UT-60D U-wing Troop Transport, was a starship model manufactured by Incom Corporation and used by the Alliance to Restore the Republic during the Galactic Civil War.", specs: {} },
  "vulture droid": { descripcion: "The Vulture-class starfighter, also known as the Variable Geometry Self-Propelled Battle Droid, Mark I, or more simply as the vulture droid, was an unmanned model of droid starfighter manufactured by Haor Chall Engineering Corporation and utilized by the Trade Federation and later the Confederacy of Independent Systems…", specs: {} },
  "y-wing": { descripcion: "The BTL Y-wing starfighter, also known to as the Y-wing starfighter/bomber, Y-wing Starfighter or more simply as the BTL-series, Y-wing fighter, or Y-wing and nicknamed the wallowing pigs, was a series of multi-role starfighter-bombers manufactured by Koensayr Manufacturing.", specs: { model: "BTL Y-wing", manufacturer: "Koensayr Manufacturing", crew: "2", passengers: "0", maxSpeed: "1000km", hyperdrive: "1.0" } },
  "z-95 headhunter": { descripcion: "The Z-95 Headhunter, also referred to as the Z-95 starfighter or simply the Z-95, was a multi-purpose starfighter jointly manufactured by Incom Corporation and Sublights Products Corporation.", specs: {} },
};
